import { KW } from '../../engine/keywords';
import type { CardDef } from '../../engine/types';
import { mkCard } from './_factory';

/** The Fixer, second set — deeper deck manipulation, discard payoffs, and Evidence banking. */
export const FIXER_CARDS_2: CardDef[] = [
  mkCard({
    id: 'fix.coldCall',
    name: 'Cold Call',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'common',
    focusCost: 0,
    onPlay: [{ op: 'drawCards', amount: 1 }],
    text: 'Costs 0 Focus. Draw 1 card.',
    flavor: 'Always be closing.',
    upgrade: {
      name: 'Cold Call+',
      onPlay: [{ op: 'drawCards', amount: 2 }],
      text: 'Costs 0 Focus. Draw 2 cards.',
    },
  }),
  mkCard({
    id: 'fix.skimTheFile',
    name: 'Skim the File',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'common',
    onPlay: [
      { op: 'drawCards', amount: 2 },
      { op: 'gainEvidence', amount: 1 },
    ],
    text: 'Draw 2 cards. Gain 1 Evidence.',
    flavor: 'You learn a lot reading the margins.',
    upgrade: {
      name: 'Skim the File+',
      onPlay: [
        { op: 'drawCards', amount: 2 },
        { op: 'gainEvidence', amount: 2 },
      ],
      text: 'Draw 2 cards. Gain 2 Evidence.',
    },
  }),
  mkCard({
    id: 'fix.evidenceLocker',
    name: 'Evidence Locker',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'common',
    onPlay: [{ op: 'gainEvidence', amount: 3 }],
    text: 'Gain 3 Evidence.',
    flavor: 'Catalogued, tagged, and conveniently forgotten.',
    upgrade: {
      name: 'Evidence Locker+',
      onPlay: [{ op: 'gainEvidence', amount: 4 }],
      text: 'Gain 4 Evidence.',
    },
  }),
  mkCard({
    id: 'fix.paperTrail',
    name: 'Paper Trail',
    character: 'fixer',
    category: 'Evidence',
    rarity: 'common',
    base: 2,
    onScore: [{ op: 'addBasePer', per: 2, source: { kind: 'evidence' } }],
    text: 'Score 2 base, plus 2 base per Evidence you have.',
    flavor: 'It all leads somewhere.',
    upgrade: {
      name: 'Paper Trail+',
      base: 2,
      onScore: [{ op: 'addBasePer', per: 3, source: { kind: 'evidence' } }],
      text: 'Score 2 base, plus 3 base per Evidence you have.',
    },
  }),
  mkCard({
    id: 'fix.buryTheLede',
    name: 'Bury the Lede',
    character: 'fixer',
    category: 'Evidence',
    rarity: 'uncommon',
    base: 4,
    onScore: [{ op: 'addBasePer', per: 3, source: { kind: 'discardPileSize' } }],
    text: 'Score 4 base, plus 3 base per card in your discard pile.',
    flavor: 'The real story is on page nineteen.',
    upgrade: {
      name: 'Bury the Lede+',
      base: 6,
      onScore: [{ op: 'addBasePer', per: 4, source: { kind: 'discardPileSize' } }],
      text: 'Score 6 base, plus 4 base per card in your discard pile.',
    },
  }),
  mkCard({
    id: 'fix.shredder',
    name: 'Feed the Shredder',
    character: 'fixer',
    category: 'Statement',
    rarity: 'uncommon',
    base: 3,
    onScore: [{ op: 'addMultPer', per: 1, source: { kind: 'discardsThisRound' } }],
    text: 'Score 3 base, plus 1 mult per time you Objected this round.',
    flavor: 'Some files are better as confetti.',
    upgrade: {
      name: 'Feed the Shredder+',
      base: 3,
      onScore: [{ op: 'addMultPer', per: 2, source: { kind: 'discardsThisRound' } }],
      text: 'Score 3 base, plus 2 mult per time you Objected this round.',
    },
  }),
  mkCard({
    id: 'fix.anonymousSource',
    name: 'Anonymous Source',
    character: 'fixer',
    category: 'Statement',
    rarity: 'common',
    base: 11,
    keywords: [KW.Hearsay],
    text: 'Score 11 base (Hearsay).',
    flavor: 'A source close to the matter.',
    upgrade: {
      name: 'Anonymous Source+',
      base: 16,
      text: 'Score 16 base (Hearsay).',
    },
  }),
  mkCard({
    id: 'fix.whisperCampaign',
    name: 'Whisper Campaign',
    character: 'fixer',
    category: 'Rhetoric',
    rarity: 'uncommon',
    base: 5,
    onScore: [
      {
        op: 'conditional',
        condition: { kind: 'cardHasKeyword', keyword: KW.Hearsay },
        then: [{ op: 'addMult', amount: 3 }],
      },
    ],
    keywords: [KW.Hearsay],
    text: 'Score 5 base (Hearsay). If this card has Hearsay, add 3 mult.',
    flavor: 'You did not hear it from me.',
  }),
  mkCard({
    id: 'fix.hushMoney',
    name: 'Hush Money',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'uncommon',
    focusCost: 1,
    onPlay: [
      { op: 'spendEvidence', amount: 2 },
      { op: 'gainRetainer', amount: 8 },
    ],
    text: 'Spend 2 Evidence. Gain 8 Retainer.',
    flavor: 'For your trouble. And your silence.',
    upgrade: {
      name: 'Hush Money+',
      onPlay: [
        { op: 'spendEvidence', amount: 2 },
        { op: 'gainRetainer', amount: 14 },
      ],
      text: 'Spend 2 Evidence. Gain 14 Retainer.',
    },
  }),
  mkCard({
    id: 'fix.blackmail',
    name: 'Blackmail',
    character: 'fixer',
    category: 'Cross',
    rarity: 'rare',
    focusCost: 2,
    base: 6,
    onScore: [{ op: 'addBasePer', per: 5, source: { kind: 'evidence' } }],
    text: 'Score 6 base, plus 5 base per Evidence you have.',
    flavor: 'I would hate for this to get out.',
    upgrade: {
      name: 'Blackmail+',
      focusCost: 2,
      base: 10,
      onScore: [{ op: 'addBasePer', per: 7, source: { kind: 'evidence' } }],
      text: 'Score 10 base, plus 7 base per Evidence you have.',
    },
  }),
  mkCard({
    id: 'fix.deepThroat',
    name: 'Deep Throat',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'rare',
    focusCost: 1,
    onPlay: [
      { op: 'drawCards', amount: 2 },
      { op: 'gainEvidence', amount: 2 },
      { op: 'gainFocus', amount: 1 },
    ],
    keywords: [KW.Stricken],
    exhausts: true,
    text: 'Draw 2 cards, gain 2 Evidence and 1 Focus. Stricken.',
    flavor: 'Follow the money.',
  }),
  mkCard({
    id: 'fix.shellGame',
    name: 'Shell Game',
    character: 'fixer',
    category: 'Statement',
    rarity: 'rare',
    focusCost: 1,
    base: 8,
    onScore: [
      {
        op: 'conditional',
        condition: { kind: 'sourceAtLeast', source: { kind: 'evidence' }, amount: 5 },
        then: [{ op: 'mulMult', factor: 2 }],
      },
    ],
    text: 'Score 8 base. If you have 5 or more Evidence, double mult.',
    flavor: 'Keep your eye on the cup. No, that one.',
    upgrade: {
      name: 'Shell Game+',
      base: 12,
      onScore: [
        {
          op: 'conditional',
          condition: { kind: 'sourceAtLeast', source: { kind: 'evidence' }, amount: 4 },
          then: [{ op: 'mulMult', factor: 2 }],
        },
      ],
      text: 'Score 12 base. If you have 4 or more Evidence, double mult.',
    },
  }),
];
