import { KW } from '../../engine/keywords';
import type { CardDef } from '../../engine/types';
import { mkCard } from './_factory';

/** The Fixer — deck manipulation and an Object/discard engine. Evidence is fuel. */
export const FIXER_CARDS: CardDef[] = [
  mkCard({
    id: 'fix.openingBrief',
    name: 'Opening Brief',
    character: 'fixer',
    category: 'Statement',
    rarity: 'starter',
    base: 8,
    text: 'Score 8 base.',
    flavor: 'Filed in triplicate.',
  }),
  mkCard({
    id: 'fix.dossier',
    name: 'The Dossier',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'starter',
    onPlay: [{ op: 'drawCards', amount: 2 }],
    text: 'Draw 2 cards.',
    flavor: 'Everything on everyone.',
  }),
  mkCard({
    id: 'fix.plant',
    name: 'Plant Evidence',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'starter',
    onPlay: [{ op: 'gainEvidence', amount: 2 }],
    text: 'Gain 2 Evidence.',
    flavor: 'It was there all along. Trust me.',
  }),
  mkCard({
    id: 'fix.insiderTip',
    name: 'Insider Tip',
    character: 'fixer',
    category: 'Evidence',
    rarity: 'common',
    base: 3,
    onScore: [{ op: 'addBasePer', per: 1, source: { kind: 'discardPileSize' } }],
    text: 'Score 3 base, plus 1 base per card in your discard pile.',
    flavor: 'A little bird told me.',
  }),
  mkCard({
    id: 'fix.quidProQuo',
    name: 'Quid Pro Quo',
    character: 'fixer',
    category: 'Statement',
    rarity: 'uncommon',
    base: 8,
    onScore: [
      { op: 'addBasePer', per: 8, source: { kind: 'discardsThisRound' } },
      { op: 'addBasePer', per: 1, source: { kind: 'evidence' } },
    ],
    text: 'Score 8 base, +8 base per Objection this round, and +1 base per Evidence.',
    flavor: 'You scratch my back...',
  }),
  mkCard({
    id: 'fix.fabricate',
    name: 'Fabricated Alibi',
    character: 'fixer',
    category: 'Statement',
    rarity: 'uncommon',
    base: 14,
    keywords: [KW.Hearsay],
    onScore: [{ op: 'gainEvidence', amount: 1 }],
    text: 'Score 14 base (Hearsay). Gain 1 Evidence.',
    flavor: 'He was with me. All night.',
  }),
  mkCard({
    id: 'fix.launder',
    name: 'Launder the Record',
    character: 'fixer',
    kind: 'action',
    category: 'Tactic',
    rarity: 'rare',
    onPlay: [
      { op: 'drawCards', amount: 1 },
      { op: 'gainFocus', amount: 1 },
      { op: 'gainEvidence', amount: 1 },
    ],
    keywords: [KW.Stricken],
    exhausts: true,
    text: 'Draw 1, gain 1 Focus and 1 Evidence. Stricken.',
    flavor: 'Now you see it...',
  }),
];
