import { KW } from '../../engine/keywords';
import type { CardDef } from '../../engine/types';
import { mkCard } from './_factory';

/** The Litigator — aggressive mult-scaling. Signature: Sustained and multiplicative blowups. */
export const LITIGATOR_CARDS: CardDef[] = [
  mkCard({
    id: 'lit.openingStatement',
    name: 'Opening Statement',
    character: 'litigator',
    category: 'Statement',
    rarity: 'starter',
    base: 6,
    text: 'Score 6 base.',
    flavor: 'The evidence will show...',
  }),
  mkCard({
    id: 'lit.crescendo',
    name: 'Crescendo',
    character: 'litigator',
    category: 'Rhetoric',
    rarity: 'starter',
    mult: 3,
    text: 'Score +3 mult.',
    flavor: 'Louder. Slower. Unstoppable.',
  }),
  mkCard({
    id: 'lit.buildup',
    name: 'Build the Tension',
    character: 'litigator',
    kind: 'action',
    category: 'Tactic',
    rarity: 'starter',
    onPlay: [{ op: 'applyStatus', target: 'self', status: KW.Sustained, amount: 2 }],
    text: 'Gain 2 Sustained.',
    flavor: 'Let it hang in the air.',
  }),
  mkCard({
    id: 'lit.grandstand',
    name: 'Grandstand',
    character: 'litigator',
    category: 'Rhetoric',
    rarity: 'common',
    onScore: [{ op: 'addMultPer', per: 1, source: { kind: 'cardsPlayedThisRound' } }],
    text: 'Score +1 mult per card already played this round.',
    flavor: 'Playing to the gallery.',
  }),
  mkCard({
    id: 'lit.escalation',
    name: 'Escalation',
    character: 'litigator',
    category: 'Rhetoric',
    rarity: 'common',
    mult: 1,
    onScore: [{ op: 'applyStatus', target: 'self', status: KW.Sustained, amount: 1 }],
    text: 'Score +1 mult. Gain 1 Sustained.',
    flavor: 'Each point builds on the last.',
  }),
  mkCard({
    id: 'lit.relentless',
    name: 'Relentless Pressure',
    character: 'litigator',
    category: 'Statement',
    rarity: 'common',
    base: 5,
    mult: 1,
    text: 'Score 5 base and +1 mult.',
    upgrade: { name: 'Relentless Pressure+', base: 7, mult: 2, text: 'Score 7 base and +2 mult.' },
    flavor: 'No pause. No mercy.',
  }),
  mkCard({
    id: 'lit.doubleDown',
    name: 'Double Down',
    character: 'litigator',
    category: 'Rhetoric',
    rarity: 'rare',
    focusCost: 2,
    onScore: [{ op: 'mulMult', factor: 2 }],
    text: 'Double your current mult.',
    upgrade: {
      name: 'Double Down+',
      focusCost: 1,
      text: 'Double your current mult. Costs 1 less Focus.',
    },
    flavor: 'All in.',
  }),
  mkCard({
    id: 'lit.thunderingClose',
    name: 'Thundering Close',
    character: 'litigator',
    category: 'Closing',
    rarity: 'rare',
    focusCost: 2,
    base: 8,
    onScore: [{ op: 'addMultPer', per: 2, source: { kind: 'statusStacks', target: 'self', status: KW.Sustained } }],
    text: 'Score 8 base, plus 2 mult per Sustained you hold.',
    flavor: 'And THAT, is reasonable doubt.',
  }),
];
