import { KW } from '../../engine/keywords';
import type { CardDef } from '../../engine/types';
import { mkCard } from './_factory';

/** Neutral cards — available to every attorney. */
export const NEUTRAL_CARDS: CardDef[] = [
  mkCard({
    id: 'neutral.assertion',
    name: 'Plain Assertion',
    category: 'Statement',
    rarity: 'starter',
    base: 6,
    text: 'Score 6 base.',
    flavor: 'Say it plainly and say it twice.',
  }),
  mkCard({
    id: 'neutral.flourish',
    name: 'Rhetorical Flourish',
    category: 'Rhetoric',
    rarity: 'starter',
    mult: 2,
    text: 'Score +2 mult.',
    flavor: 'It is not what you say, but how.',
  }),
  mkCard({
    id: 'neutral.objection',
    name: 'Objection',
    kind: 'action',
    category: 'Objection',
    rarity: 'starter',
    keywords: [],
    onPlay: [{ op: 'reduceConviction', amount: 7 }],
    text: 'Reduce Conviction by 7.',
    flavor: 'Objection! Relevance, Your Honor.',
  }),
  mkCard({
    id: 'neutral.research',
    name: 'Legal Research',
    kind: 'action',
    category: 'Tactic',
    onPlay: [
      { op: 'drawCards', amount: 2 },
      { op: 'gainEvidence', amount: 1 },
    ],
    text: 'Draw 2 cards. Gain 1 Evidence.',
    flavor: 'The library never sleeps.',
  }),
  mkCard({
    id: 'neutral.steady',
    name: 'Steady Nerves',
    kind: 'action',
    category: 'Tactic',
    onPlay: [{ op: 'gainComposure', amount: 9 }],
    text: 'Gain 9 Composure.',
    flavor: 'Breathe. The jury is watching.',
  }),
  mkCard({
    id: 'neutral.exhibit',
    name: 'Enter Exhibit',
    category: 'Evidence',
    base: 4,
    onScore: [{ op: 'gainEvidence', amount: 1 }],
    text: 'Score 4 base. Gain 1 Evidence.',
    flavor: "Marked for identification as Defense Exhibit 'A'.",
  }),
  mkCard({
    id: 'neutral.leadingQuestion',
    name: 'Leading Question',
    category: 'Cross',
    base: 3,
    keywords: [KW.Leading],
    text: 'Score 3 base. Leading.',
    flavor: "Isn't it true that...?",
  }),
  mkCard({
    id: 'neutral.testimony',
    name: 'Sworn Testimony',
    category: 'Statement',
    focusCost: 2,
    base: 13,
    text: 'Score 13 base.',
    flavor: 'The whole truth, and nothing but.',
  }),
  mkCard({
    id: 'neutral.rumor',
    name: 'Unsubstantiated Rumor',
    category: 'Statement',
    rarity: 'uncommon',
    base: 20,
    keywords: [KW.Hearsay],
    text: 'Score 20 base. Hearsay — needs Evidence to count.',
    flavor: 'A friend of a friend swears it is true.',
  }),
  mkCard({
    id: 'neutral.closingArgument',
    name: 'Closing Argument',
    category: 'Closing',
    rarity: 'uncommon',
    focusCost: 2,
    base: 4,
    onScore: [{ op: 'addBasePer', per: 4, source: { kind: 'cardsPlayedThisRound' } }],
    text: 'Score 4 base, plus 4 base per card already played this round.',
    flavor: 'In conclusion, ladies and gentlemen...',
  }),
  mkCard({
    id: 'neutral.crossExamine',
    name: 'Cross-Examination',
    kind: 'action',
    category: 'Cross',
    rarity: 'common',
    onPlay: [{ op: 'reduceConviction', amount: 4 }, { op: 'gainEvidence', amount: 1 }],
    text: 'Reduce Conviction by 4. Gain 1 Evidence.',
    flavor: 'Answer the question that was asked.',
  }),
  mkCard({
    id: 'neutral.precedentCite',
    name: 'Cite Precedent',
    category: 'Statement',
    rarity: 'common',
    base: 5,
    onScore: [{ op: 'addBasePer', per: 2, source: { kind: 'evidence' } }],
    text: 'Score 5 base, plus 2 base per Evidence you hold.',
    flavor: 'As established in Marbury, Your Honor.',
  }),
];
