import { KW } from '../../engine/keywords';
import type { CardDef } from '../../engine/types';
import { mkCard } from './_factory';

/** The Showman, second set — one enormous argument: size scaling, retriggers, big swings. */
export const SHOWMAN_CARDS_2: CardDef[] = [
  mkCard({
    id: 'show.warmUp',
    name: 'Warm Up the Room',
    character: 'showman',
    category: 'Statement',
    rarity: 'common',
    base: 4,
    onScore: [
      {
        op: 'conditional',
        condition: { kind: 'firstCardOfArgument' },
        then: [{ op: 'addBase', amount: 6 }],
      },
    ],
    text: 'Score 4 base. If this is the first card of the argument, add 6 base.',
    flavor: 'A little something to start.',
    upgrade: {
      name: 'Warm Up the Room+',
      base: 6,
      onScore: [
        {
          op: 'conditional',
          condition: { kind: 'firstCardOfArgument' },
          then: [{ op: 'addBase', amount: 9 }],
        },
      ],
      text: 'Score 6 base. If this is the first card of the argument, add 9 base.',
    },
  }),
  mkCard({
    id: 'show.crescendo',
    name: 'Crescendo',
    character: 'showman',
    category: 'Rhetoric',
    rarity: 'common',
    base: 2,
    onScore: [{ op: 'addBasePer', per: 4, source: { kind: 'argumentSize' } }],
    text: 'Score 2 base, plus 4 base per card in this argument.',
    flavor: 'Louder. Louder still.',
    upgrade: {
      name: 'Crescendo+',
      base: 2,
      onScore: [{ op: 'addBasePer', per: 6, source: { kind: 'argumentSize' } }],
      text: 'Score 2 base, plus 6 base per card in this argument.',
    },
  }),
  mkCard({
    id: 'show.bigVoice',
    name: 'Big Voice',
    character: 'showman',
    category: 'Rhetoric',
    rarity: 'common',
    base: 5,
    mult: 2,
    text: 'Score 5 base and +2 mult.',
    flavor: 'They can hear you in the back row.',
    upgrade: {
      name: 'Big Voice+',
      base: 8,
      mult: 3,
      text: 'Score 8 base and +3 mult.',
    },
  }),
  mkCard({
    id: 'show.soliloquy',
    name: 'Soliloquy',
    character: 'showman',
    category: 'Rhetoric',
    rarity: 'uncommon',
    focusCost: 2,
    onScore: [{ op: 'addMultPer', per: 2, source: { kind: 'argumentSize' } }],
    text: 'Score +2 mult per card in this argument.',
    flavor: 'To convict, or not to convict.',
    upgrade: {
      name: 'Soliloquy+',
      focusCost: 2,
      onScore: [{ op: 'addMultPer', per: 3, source: { kind: 'argumentSize' } }],
      text: 'Score +3 mult per card in this argument.',
    },
  }),
  mkCard({
    id: 'show.doubleTake',
    name: 'Double Take',
    character: 'showman',
    category: 'Statement',
    rarity: 'uncommon',
    focusCost: 2,
    base: 7,
    onScore: [{ op: 'retrigger', times: 1 }],
    text: 'Score 7 base, then score this card again.',
    flavor: 'Wait. Did everyone catch that? Let me repeat it.',
    upgrade: {
      name: 'Double Take+',
      focusCost: 2,
      base: 11,
      onScore: [{ op: 'retrigger', times: 1 }],
      text: 'Score 11 base, then score this card again.',
    },
  }),
  mkCard({
    id: 'show.callback',
    name: 'Callback',
    character: 'showman',
    category: 'Rhetoric',
    rarity: 'uncommon',
    base: 4,
    onScore: [
      {
        op: 'conditional',
        condition: { kind: 'sourceAtLeast', source: { kind: 'argumentSize' }, amount: 5 },
        then: [{ op: 'retrigger', times: 1 }],
      },
    ],
    text: 'Score 4 base. If this argument has 5 or more cards, score it again.',
    flavor: 'Remember what I said earlier? Watch this.',
    upgrade: {
      name: 'Callback+',
      base: 6,
      onScore: [
        {
          op: 'conditional',
          condition: { kind: 'sourceAtLeast', source: { kind: 'argumentSize' }, amount: 4 },
          then: [{ op: 'retrigger', times: 1 }],
        },
      ],
      text: 'Score 6 base. If this argument has 4 or more cards, score it again.',
    },
  }),
  mkCard({
    id: 'show.showstopper',
    name: 'Showstopper',
    character: 'showman',
    category: 'Statement',
    rarity: 'common',
    focusCost: 2,
    base: 22,
    keywords: [KW.Stricken],
    exhausts: true,
    text: 'Score 22 base. Stricken.',
    flavor: 'Hold for applause.',
    upgrade: {
      name: 'Showstopper+',
      focusCost: 2,
      base: 32,
      exhausts: true,
      addKeywords: [KW.Stricken],
      text: 'Score 32 base. Stricken.',
    },
  }),
  mkCard({
    id: 'show.bowAndExit',
    name: 'Bow and Exit',
    character: 'showman',
    category: 'Closing',
    rarity: 'uncommon',
    focusCost: 1,
    onScore: [{ op: 'addBasePer', per: 5, source: { kind: 'argumentSize' } }],
    keywords: [KW.Stricken],
    exhausts: true,
    text: 'Score 5 base per card in this argument. Stricken.',
    flavor: 'Leave them wanting more.',
    upgrade: {
      name: 'Bow and Exit+',
      focusCost: 1,
      onScore: [{ op: 'addBasePer', per: 8, source: { kind: 'argumentSize' } }],
      exhausts: true,
      addKeywords: [KW.Stricken],
      text: 'Score 8 base per card in this argument. Stricken.',
    },
  }),
  mkCard({
    id: 'show.finale',
    name: 'Grand Finale',
    character: 'showman',
    category: 'Closing',
    rarity: 'rare',
    focusCost: 3,
    onScore: [{ op: 'addMultPer', per: 3, source: { kind: 'argumentSize' } }],
    keywords: [KW.Stricken],
    exhausts: true,
    text: 'Score +3 mult per card in this argument. Stricken.',
    flavor: 'And for my final act...',
    upgrade: {
      name: 'Grand Finale+',
      focusCost: 3,
      onScore: [{ op: 'addMultPer', per: 4, source: { kind: 'argumentSize' } }],
      exhausts: true,
      addKeywords: [KW.Stricken],
      text: 'Score +4 mult per card in this argument. Stricken.',
    },
  }),
  mkCard({
    id: 'show.magnumOpus',
    name: 'Magnum Opus',
    character: 'showman',
    category: 'Closing',
    rarity: 'rare',
    focusCost: 3,
    base: 10,
    onScore: [
      {
        op: 'conditional',
        condition: { kind: 'sourceAtLeast', source: { kind: 'argumentSize' }, amount: 7 },
        then: [{ op: 'mulMult', factor: 3 }],
        else: [{ op: 'mulMult', factor: 2 }],
      },
    ],
    text: 'Score 10 base. Triple mult if this argument has 7 or more cards, otherwise double mult.',
    flavor: 'My finest work, summarized for the jury.',
  }),
  mkCard({
    id: 'show.oneManShow',
    name: 'One-Man Show',
    character: 'showman',
    category: 'Statement',
    rarity: 'rare',
    focusCost: 3,
    base: 40,
    onScore: [
      {
        op: 'conditional',
        condition: { kind: 'sourceAtMost', source: { kind: 'argumentSize' }, amount: 1 },
        then: [{ op: 'addBase', amount: 25 }],
      },
    ],
    keywords: [KW.Stricken],
    exhausts: true,
    text: 'Score 40 base. If this is the only card in the argument, add 25 base. Stricken.',
    flavor: 'No co-counsel. No notes. Just me.',
    upgrade: {
      name: 'One-Man Show+',
      focusCost: 3,
      base: 55,
      onScore: [
        {
          op: 'conditional',
          condition: { kind: 'sourceAtMost', source: { kind: 'argumentSize' }, amount: 1 },
          then: [{ op: 'addBase', amount: 35 }],
        },
      ],
      exhausts: true,
      addKeywords: [KW.Stricken],
      text: 'Score 55 base. If this is the only card in the argument, add 35 base. Stricken.',
    },
  }),
  mkCard({
    id: 'show.standingRoom',
    name: 'Standing Room Only',
    character: 'showman',
    category: 'Rhetoric',
    rarity: 'uncommon',
    base: 6,
    onScore: [
      { op: 'addBasePer', per: 2, source: { kind: 'argumentSize' } },
      { op: 'addMultPer', per: 1, source: { kind: 'argumentSize' } },
    ],
    text: 'Score 6 base, plus 2 base and +1 mult per card in this argument.',
    flavor: 'Sold out. Every seat.',
    upgrade: {
      name: 'Standing Room Only+',
      base: 6,
      onScore: [
        { op: 'addBasePer', per: 3, source: { kind: 'argumentSize' } },
        { op: 'addMultPer', per: 1, source: { kind: 'argumentSize' } },
      ],
      text: 'Score 6 base, plus 3 base and +1 mult per card in this argument.',
    },
  }),
];
