import type { MotionDef } from '../engine/types';

/** One-shot consumables. Combat motions resolve into the trial; map motions act on the run. */
export const ALL_MOTIONS: MotionDef[] = [
  {
    id: 'mo.continuance',
    name: 'Motion for Continuance',
    rarity: 'common',
    text: 'Gain 2 Focus and draw 2 cards.',
    usage: 'combat',
    combatEffects: [
      { op: 'gainFocus', amount: 2 },
      { op: 'drawCards', amount: 2 },
    ],
    cost: 45,
    flavor: 'Buy yourself a moment.',
  },
  {
    id: 'mo.dismiss',
    name: 'Motion to Dismiss',
    rarity: 'common',
    text: 'Reduce Conviction by 25.',
    usage: 'combat',
    combatEffects: [{ op: 'reduceConviction', amount: 25 }],
    cost: 50,
    flavor: 'Your Honor, the State has no case.',
  },
  {
    id: 'mo.subpoena',
    name: 'Subpoena',
    rarity: 'common',
    text: 'Gain 3 Evidence.',
    usage: 'combat',
    combatEffects: [{ op: 'gainEvidence', amount: 3 }],
    cost: 40,
    flavor: 'You are hereby commanded to appear.',
  },
  {
    id: 'mo.suppress',
    name: 'Motion to Suppress',
    rarity: 'uncommon',
    text: 'Gain 4 Sustained and reduce Conviction by 10.',
    usage: 'combat',
    combatEffects: [
      { op: 'applyStatus', target: 'self', status: 'sustained', amount: 4 },
      { op: 'reduceConviction', amount: 10 },
    ],
    cost: 65,
    flavor: 'That evidence is inadmissible.',
  },
  {
    id: 'mo.recessChambers',
    name: 'Request a Recess',
    rarity: 'common',
    text: 'Heal 20 Composure (used on the map).',
    usage: 'map',
    mapOutcomes: [{ kind: 'healComposure', amount: 20 }],
    cost: 40,
    flavor: 'We will reconvene at nine.',
  },
  {
    id: 'mo.amendment',
    name: 'Amend the Filing',
    rarity: 'uncommon',
    text: 'Upgrade a random card (used on the map).',
    usage: 'map',
    mapOutcomes: [{ kind: 'upgradeRandomCard' }],
    cost: 70,
    flavor: 'A small correction, with large consequences.',
  },
  {
    id: 'mo.expungement',
    name: 'Expungement Order',
    rarity: 'uncommon',
    text: 'Remove a random card from your deck (used on the map).',
    usage: 'map',
    mapOutcomes: [{ kind: 'removeRandomCard' }],
    cost: 75,
    flavor: 'Let the record reflect: nothing.',
  },
];
