import { KW } from '../../engine/keywords';
import type { EnemyDef } from '../../engine/types';

/**
 * Prosecution encounters across three acts (Small Claims → District → Supreme).
 * Normal trials, elites, and bosses that mutate the rules.
 */
export const ALL_ENEMIES: EnemyDef[] = [
  // ───────────── Act 1 — Small Claims Court ─────────────
  {
    id: 'a1.shoplifting',
    name: 'The Shoplifting Charge',
    kind: 'trial',
    act: 1,
    baseDoubtTarget: 60,
    targetRampPerRound: 2,
    maxRounds: 9,
    baseConvictionPerRound: 4,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Present Evidence', value: 5 },
      { weight: 1, kind: 'raiseTarget', label: 'Belabor the Point', value: 6 },
      { weight: 1, kind: 'status', label: 'Fluster', value: 1, status: KW.Rattled },
    ],
    flavor: 'A pack of gum and a world of trouble.',
  },
  {
    id: 'a1.noise',
    name: 'The Noise Complaint',
    kind: 'trial',
    act: 1,
    baseDoubtTarget: 54,
    targetRampPerRound: 3,
    maxRounds: 8,
    baseConvictionPerRound: 4,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Cite the Ordinance', value: 6 },
      { weight: 2, kind: 'raiseTarget', label: 'Call More Neighbors', value: 7 },
    ],
    flavor: 'It was a Tuesday. At noon.',
  },
  {
    id: 'a1.parking',
    name: 'The Parking Dispute',
    kind: 'trial',
    act: 1,
    baseDoubtTarget: 68,
    targetRampPerRound: 2,
    maxRounds: 9,
    baseConvictionPerRound: 5,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Wave the Ticket', value: 6 },
      { weight: 1, kind: 'overrule', label: 'Strike That', value: 1 },
    ],
    flavor: 'The lines were merely a suggestion.',
  },
  {
    id: 'a1.elite.zealousDA',
    name: 'A Zealous Prosecutor',
    kind: 'elite',
    act: 1,
    baseDoubtTarget: 105,
    targetRampPerRound: 4,
    maxRounds: 10,
    baseConvictionPerRound: 7,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Hammer Home', value: 9 },
      { weight: 2, kind: 'overrule', label: 'Objection!', value: 1 },
      {
        weight: 1,
        kind: 'witness',
        label: 'Call a Witness',
        value: 0,
        witness: { name: 'Eyewitness', convictionPerRound: 4, health: 20 },
      },
    ],
    flavor: 'Fresh out of law school and out for blood.',
  },
  {
    id: 'a1.boss.judgeStern',
    name: 'Judge Stern',
    kind: 'boss',
    act: 1,
    baseDoubtTarget: 135,
    targetRampPerRound: 4,
    maxRounds: 11,
    baseConvictionPerRound: 6,
    rules: { multCap: 9 },
    intents: [
      { weight: 3, kind: 'conviction', label: 'Sustain the State', value: 10 },
      { weight: 2, kind: 'raiseTarget', label: 'Raise the Bar', value: 10 },
      { weight: 2, kind: 'overrule', label: 'Overruled!', value: 2 },
    ],
    flavor: 'A biased judge. Your mult is capped at 9.',
  },

  // ───────────── Act 2 — District Court ─────────────
  {
    id: 'a2.fraud',
    name: 'The Fraud Indictment',
    kind: 'trial',
    act: 2,
    baseDoubtTarget: 150,
    targetRampPerRound: 5,
    maxRounds: 10,
    baseConvictionPerRound: 8,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Trace the Funds', value: 11 },
      { weight: 2, kind: 'raiseTarget', label: 'Subpoena Records', value: 12 },
      { weight: 1, kind: 'status', label: 'Intimidate', value: 2, status: KW.Rattled },
    ],
    flavor: 'Follow the money. It always tells.',
  },
  {
    id: 'a2.assault',
    name: 'The Assault Case',
    kind: 'trial',
    act: 2,
    baseDoubtTarget: 165,
    targetRampPerRound: 4,
    maxRounds: 10,
    baseConvictionPerRound: 9,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Show the Photos', value: 12 },
      { weight: 2, kind: 'overrule', label: 'Strike the Testimony', value: 2 },
    ],
    flavor: 'The defendant says it was self-defense.',
  },
  {
    id: 'a2.elite.expertWitness',
    name: 'The Expert Witness',
    kind: 'elite',
    act: 2,
    baseDoubtTarget: 220,
    targetRampPerRound: 6,
    maxRounds: 11,
    baseConvictionPerRound: 10,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Cite the Study', value: 14 },
      {
        weight: 2,
        kind: 'witness',
        label: 'Take the Stand',
        value: 0,
        witness: { name: 'Forensic Expert', convictionPerRound: 7, health: 40 },
      },
      { weight: 1, kind: 'status', label: 'Condescend', value: 2, status: KW.Contempt },
    ],
    flavor: 'Credentials longer than the indictment.',
  },
  {
    id: 'a2.boss.hungJury',
    name: 'The Hung Jury',
    kind: 'boss',
    act: 2,
    baseDoubtTarget: 250,
    targetRampPerRound: 6,
    maxRounds: 12,
    baseConvictionPerRound: 9,
    rules: { doubtDrainPerRound: 7 },
    intents: [
      { weight: 3, kind: 'conviction', label: 'Sway the Holdouts', value: 13 },
      { weight: 2, kind: 'drain', label: 'Reconsider', value: 10 },
      { weight: 2, kind: 'raiseTarget', label: 'Deadlock', value: 14 },
    ],
    flavor: 'A hostile jury. You lose 7 Doubt every round.',
  },

  // ───────────── Act 3 — Supreme Court ─────────────
  {
    id: 'a3.appeal',
    name: 'The Constitutional Appeal',
    kind: 'trial',
    act: 3,
    baseDoubtTarget: 300,
    targetRampPerRound: 7,
    maxRounds: 11,
    baseConvictionPerRound: 12,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Invoke Doctrine', value: 16 },
      { weight: 2, kind: 'raiseTarget', label: 'Cite the Framers', value: 16 },
      { weight: 1, kind: 'overrule', label: 'Strike', value: 2 },
    ],
    flavor: 'The stakes could not be higher.',
  },
  {
    id: 'a3.murder',
    name: 'The Capital Case',
    kind: 'trial',
    act: 3,
    baseDoubtTarget: 330,
    targetRampPerRound: 6,
    maxRounds: 12,
    baseConvictionPerRound: 13,
    intents: [
      { weight: 3, kind: 'conviction', label: 'Demand Justice', value: 18 },
      { weight: 2, kind: 'status', label: 'Rattle', value: 2, status: KW.Rattled },
      {
        weight: 1,
        kind: 'witness',
        label: 'Star Witness',
        value: 0,
        witness: { name: 'Star Witness', convictionPerRound: 9, health: 60 },
      },
    ],
    flavor: 'Everything rests on reasonable doubt.',
  },
  {
    id: 'a3.elite.mediaCircus',
    name: 'The Media Circus',
    kind: 'elite',
    act: 3,
    baseDoubtTarget: 360,
    targetRampPerRound: 8,
    maxRounds: 12,
    baseConvictionPerRound: 13,
    rules: { convictionRamp: 2 },
    intents: [
      { weight: 3, kind: 'conviction', label: 'Trial by Headline', value: 18 },
      { weight: 2, kind: 'overrule', label: 'Leak to the Press', value: 3 },
      { weight: 2, kind: 'status', label: 'Public Pressure', value: 3, status: KW.Contempt },
    ],
    flavor: 'Cameras in the courtroom change everything.',
  },
  {
    id: 'a3.boss.chiefJustice',
    name: 'The Chief Justice',
    kind: 'boss',
    act: 3,
    baseDoubtTarget: 430,
    targetRampPerRound: 8,
    maxRounds: 13,
    baseConvictionPerRound: 12,
    rules: { composureDrainPerRound: 3, convictionRamp: 2 },
    intents: [
      { weight: 3, kind: 'conviction', label: 'Final Authority', value: 20 },
      { weight: 2, kind: 'raiseTarget', label: 'Set Precedent', value: 18 },
      { weight: 2, kind: 'overrule', label: 'The Last Word', value: 3 },
    ],
    flavor: 'The bench drains 3 Composure each round. No appeals beyond this.',
  },
];
